version: "3.8"

networks:
  app_network:
    driver: bridge

services:
  chat_frontend:
    container_name: ${COMPOSE_PROJECT_NAME}_frontend
    image: myobandar/ekballo_chat_frontend
    hostname: chat_frontend
    ports:
      - ${FRONT_HOST_PORT}:${CONTAINER_NUXT_PORT}
    volumes:
      - ${FRONT_SRC_PATH_HOST}:/usr/src/chat-frontend
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=${CONTAINER_NUXT_PORT}
    networks:
      - app_network
    tty: true

  chat_backend:
    container_name: ${COMPOSE_PROJECT_NAME}chat_backend
    image: myobandar/ekballo_chat_backend
    hostname: chat_backend
    ports:
      - ${BACK_HOST_PORT}:${CONTAINER_PHP_PORT}
    volumes:
      - ${BACK_SRC_PATH_HOST}:/usr/src/chat-backend
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=${CONTAINER_PHP_PORT}
    networks:
      - app_network
    tty: true